# Generated by Django 5.0 on 2024-01-05 11:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('name_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('bottling_date', models.DateField(verbose_name='Дата розлива')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('description_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вина',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WineMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Виномаркет',
                'verbose_name_plural': 'Виномаркеты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WineMarketStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=False, verbose_name='В наличии')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='wines.winemarket', verbose_name='Маркет')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wines.wine', verbose_name='Вино')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Наличие вин в маркетах',
                'ordering': ('in_stock',),
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='markets',
            field=models.ManyToManyField(through='wines.WineMarketStock', to='wines.winemarket', verbose_name='Маркеты'),
        ),
        migrations.AddConstraint(
            model_name='winemarketstock',
            constraint=models.UniqueConstraint(fields=('wine', 'market'), name='unique_record'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_vector'], name='wines_wine_name_ve_09c6d9_gin'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_vector'], name='wines_wine_descrip_6eff91_gin'),
        ),
    ]
