# Generated by Django 5.0 on 2024-01-05 04:13
import datetime
import json
import random

from django.db import migrations


WINE_DATA_FILEPATH = './server/wines/data/wine_data.json'

with open(WINE_DATA_FILEPATH, 'r') as data_file:
    wine_data = json.load(data_file)


MARKET_DATA_FILEPATH = './server/wines/data/market_data.json'

with open(MARKET_DATA_FILEPATH, 'r') as data_file:
    market_data = json.load(data_file)


def get_random_price() -> int:
    """Возвращает рандомную цену."""
    return random.randint(150, 10000)


def get_random_date() -> datetime:
    """Возвращает рандомую дату."""
    return datetime.date(
        year=random.randint(2020, 2023),
        month=random.randint(1, 12),
        day=random.randint(1, 28),
    )


def load_wines_data(apps, schema_editor):
    """Загрузка модели Wines данными."""
    Wine = apps.get_model('wines', 'Wine')

    for item in wine_data:
        wine = Wine(
            **item,
            price=get_random_price(),
            bottling_date=get_random_date(),
        )
        wine.save()


def reverse_load_wines_data(apps, schema_editor):
    """Откат загрузки модели Wine."""
    Wine = apps.get_model('wines', 'Wine')
    Wine.objects.all().delete()


def load_markets_data(apps, schema_editor):
    """Загрузка модели WineMarket данными."""
    WineMarket = apps.get_model('wines', 'WineMarket')

    for item in market_data:
        market = WineMarket(
            **item,
        )
        market.save()


def reverse_load_markets_data(apps, schema_editor):
    """Откат загрузки модели WineMarket."""
    WineMarket = apps.get_model('wines', 'WineMarket')
    WineMarket.objects.all().delete()


def load_wine_and_market_data(apps, schema_editor):
    """Загрузка модели WineMarketStock данными."""
    WineMarketStock = apps.get_model('wines', 'WineMarketStock')
    Wine = apps.get_model('wines', 'Wine')
    WineMarket = apps.get_model('wines', 'WineMarket')

    wines = Wine.objects.all()
    markets = WineMarket.objects.all()
    in_stock_list = []

    for market in markets:
        random_wines = [random.choice(wines) for _ in range(random.randint(1, 11))]
        for wine in random_wines:
            in_stock = WineMarketStock(
                market=market,
                wine=wine,
                in_stock=random.choice([True, False]),
            )
            in_stock_list.append(in_stock)

    WineMarketStock.objects.bulk_create(in_stock_list, ignore_conflicts=True)


def reverse_load_wine_and_market_data(apps, schema_editor):
    """Откат загрузки модели WineMarket."""
    WineMarketStock = apps.get_model('wines', 'WineMarketStock')
    WineMarketStock.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_wines_data, reverse_load_wines_data),
        migrations.RunPython(load_markets_data, reverse_load_markets_data),
        migrations.RunPython(load_wine_and_market_data, reverse_load_wine_and_market_data),
    ]
